/**
 * MEET Demo Data
 * Realistic seed data centered around African creators, founders and professionals majorly from Nairobi, Kenya.
 */

import type { Profile, Event, Community, Activity, Place, Notification, Post } from '@/types'

// --- PROFILES ---
export const DEMO_PROFILES: Profile[] = [
  {
    id: 'p1',
    username: 'amara.wanjiku',
    full_name: 'Amara Wanjiku',
    first_name: 'Amara',
    last_name: 'Wanjiku',
    avatar_url: '/avatars/amara.jpg',
    cover_url: null,
    bio: 'Lead UX Designer @ iHub Nairobi. Crafting intuitive digital experiences for African tech startups. Design mentor & speaker.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2921,
    longitude: 36.8219,
    account_type: 'creator',
    is_verified: true,
    is_private: false,
    website: 'https://amarawanjiku.design',
    followers_count: 5840,
    following_count: 480,
    connections_count: 420,
    posts_count: 168,
    created_at: '2024-01-15T08:00:00Z',
    updated_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 'p2',
    username: 'kwame.mensah',
    full_name: 'Kwame Mensah',
    first_name: 'Kwame',
    last_name: 'Mensah',
    avatar_url: '/avatars/kwame.jpg',
    cover_url: null,
    bio: "Visual storyteller & documentary photographer based in Westlands, Nairobi. Capturing East Africa's wildlife, people and vibrant street culture.",
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2684,
    longitude: 36.8069,
    account_type: 'creator',
    is_verified: true,
    is_private: false,
    website: 'https://kwamemensah.photos',
    followers_count: 14200,
    following_count: 890,
    connections_count: 720,
    posts_count: 412,
    created_at: '2023-08-20T08:00:00Z',
    updated_at: '2023-08-20T08:00:00Z',
  },
  {
    id: 'p3',
    username: 'sadia.ibrahim',
    full_name: 'Sadia Ibrahim',
    first_name: 'Sadia',
    last_name: 'Ibrahim',
    avatar_url: '/avatars/sadia.jpg',
    cover_url: null,
    bio: 'Founder @ PayAfrica | Building modern cross-border financial rails for 300M+ Africans. Forbes 30 Under 30 Africa. Nairobi & Lagos.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2975,
    longitude: 36.8182,
    account_type: 'business',
    is_verified: true,
    is_private: false,
    website: 'https://payafrica.co',
    followers_count: 38500,
    following_count: 1100,
    connections_count: 2150,
    posts_count: 245,
    created_at: '2023-03-10T08:00:00Z',
    updated_at: '2023-03-10T08:00:00Z',
  },
  {
    id: 'p4',
    username: 'david.kamau',
    full_name: 'David Kamau',
    first_name: 'David',
    last_name: 'Kamau',
    avatar_url: '/avatars/david.jpg',
    cover_url: null,
    bio: 'Senior Backend Engineer @ Safaricom. M-Pesa core infrastructure, distributed systems & cloud architecture. Weekend hiker across Ngong Hills.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3040,
    longitude: 36.8067,
    account_type: 'personal',
    is_verified: true,
    is_private: false,
    website: null,
    followers_count: 3620,
    following_count: 730,
    connections_count: 610,
    posts_count: 94,
    created_at: '2024-02-01T08:00:00Z',
    updated_at: '2024-02-01T08:00:00Z',
  },
  {
    id: 'p5',
    username: 'aisha.mwangi',
    full_name: 'Aisha Mwangi',
    first_name: 'Aisha',
    last_name: 'Mwangi',
    avatar_url: '/avatars/aisha.jpg',
    cover_url: null,
    bio: 'Afro-soul vocalist, producer & sound designer. Blending traditional Kenyan instruments with electronic grooves. Studio sessions in Kileleshwa.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2772,
    longitude: 36.8167,
    account_type: 'creator',
    is_verified: true,
    is_private: false,
    website: 'https://aishamwangi.ke',
    followers_count: 9400,
    following_count: 420,
    connections_count: 380,
    posts_count: 210,
    created_at: '2023-11-05T08:00:00Z',
    updated_at: '2023-11-05T08:00:00Z',
  },
  {
    id: 'p6',
    username: 'brian.kipkemboi',
    full_name: 'Brian Kipkemboi',
    first_name: 'Brian',
    last_name: 'Kipkemboi',
    avatar_url: '/avatars/brian.jpg',
    cover_url: null,
    bio: 'Marathoner & athletics coach. Running trails through Karura Forest & Ngong Hills. Building Nairobi Runner Community.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2321,
    longitude: 36.8264,
    account_type: 'personal',
    is_verified: true,
    is_private: false,
    website: null,
    followers_count: 7800,
    following_count: 360,
    connections_count: 510,
    posts_count: 142,
    created_at: '2023-09-22T08:00:00Z',
    updated_at: '2023-09-22T08:00:00Z',
  },
  {
    id: 'p7',
    username: 'faith.chebet',
    full_name: 'Faith Chebet',
    first_name: 'Faith',
    last_name: 'Chebet',
    avatar_url: '/avatars/faith.jpg',
    cover_url: null,
    bio: 'Founder @ ShambaPulse | Climate resilience and IoT sensor solutions for smallholder farmers across East Africa. Gigiri, Nairobi.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2286,
    longitude: 36.8093,
    account_type: 'business',
    is_verified: true,
    is_private: false,
    website: 'https://shambapulse.africa',
    followers_count: 6420,
    following_count: 510,
    connections_count: 670,
    posts_count: 115,
    created_at: '2024-03-01T08:00:00Z',
    updated_at: '2024-03-01T08:00:00Z',
  },
  {
    id: 'p8',
    username: 'tariq.otieno',
    full_name: 'Tariq Otieno',
    first_name: 'Tariq',
    last_name: 'Otieno',
    avatar_url: '/avatars/tariq.jpg',
    cover_url: null,
    bio: 'AI Research Scientist @ Nairobi AI Lab. Specializing in low-resource African language models (Swahili, Sheng, Luganda). Tech writer & open source contributor.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2684,
    longitude: 36.8069,
    account_type: 'creator',
    is_verified: true,
    is_private: false,
    website: 'https://tariqotieno.ai',
    followers_count: 8900,
    following_count: 620,
    connections_count: 890,
    posts_count: 134,
    created_at: '2023-06-12T08:00:00Z',
    updated_at: '2023-06-12T08:00:00Z',
  },
  {
    id: 'p9',
    username: 'sharon.achieng',
    full_name: 'Sharon Achieng',
    first_name: 'Sharon',
    last_name: 'Achieng',
    avatar_url: '/avatars/sharon.jpg',
    cover_url: null,
    bio: 'Founder @ Nairobi Women in Tech. Senior Product Manager & advocate for inclusive digital leadership across Africa. Westlands, Nairobi.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2650,
    longitude: 36.8050,
    account_type: 'creator',
    is_verified: true,
    is_private: false,
    website: 'https://nairobiwomenintech.org',
    followers_count: 11200,
    following_count: 850,
    connections_count: 1240,
    posts_count: 198,
    created_at: '2023-04-18T08:00:00Z',
    updated_at: '2023-04-18T08:00:00Z',
  },
  {
    id: 'p10',
    username: 'njeri.muthoni',
    full_name: 'Njeri Muthoni',
    first_name: 'Njeri',
    last_name: 'Muthoni',
    avatar_url: '/avatars/njeri.jpg',
    cover_url: null,
    bio: 'Contemporary fashion designer & creative director @ KikoWear. Blending Kitenge textiles with high-street urban aesthetics. Lavington, Nairobi.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2850,
    longitude: 36.7720,
    account_type: 'creator',
    is_verified: true,
    is_private: false,
    website: 'https://kikowear.co.ke',
    followers_count: 16500,
    following_count: 740,
    connections_count: 820,
    posts_count: 312,
    created_at: '2023-05-14T08:00:00Z',
    updated_at: '2023-05-14T08:00:00Z',
  },
  {
    id: 'p11',
    username: 'juma.omondi',
    full_name: 'Juma Omondi',
    first_name: 'Juma',
    last_name: 'Omondi',
    avatar_url: '/avatars/juma.jpg',
    cover_url: null,
    bio: 'Kenya National Barista Champion. Founder @ Nairobi Coffee Roasters. Championing Nyeri AA and Mt. Kenya specialty single-origins in Karen, Nairobi.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3197,
    longitude: 36.7065,
    account_type: 'business',
    is_verified: true,
    is_private: false,
    website: 'https://nairobroasters.com',
    followers_count: 7200,
    following_count: 410,
    connections_count: 530,
    posts_count: 154,
    created_at: '2023-07-29T08:00:00Z',
    updated_at: '2023-07-29T08:00:00Z',
  },
  {
    id: 'p12',
    username: 'zawadi.naliaka',
    full_name: 'Zawadi Naliaka',
    first_name: 'Zawadi',
    last_name: 'Naliaka',
    avatar_url: '/avatars/zawadi.jpg',
    cover_url: null,
    bio: 'Wildlife conservation photojournalist. Documenting East African ecosystems from Nairobi National Park to the Mara. National Geographic contributor.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3650,
    longitude: 36.8500,
    account_type: 'creator',
    is_verified: true,
    is_private: false,
    website: 'https://zawadiphoto.ke',
    followers_count: 22400,
    following_count: 610,
    connections_count: 940,
    posts_count: 285,
    created_at: '2023-02-11T08:00:00Z',
    updated_at: '2023-02-11T08:00:00Z',
  },
  {
    id: 'p13',
    username: 'dennis.mutua',
    full_name: 'Dennis Mutua',
    first_name: 'Dennis',
    last_name: 'Mutua',
    avatar_url: '/avatars/dennis.jpg',
    cover_url: null,
    bio: '3D Animator & Indie Game Developer @ LevelUp Kenya. Building African mythology video games with Unreal Engine 5. Parklands, Nairobi.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2610,
    longitude: 36.8190,
    account_type: 'creator',
    is_verified: true,
    is_private: false,
    website: 'https://levelupkenya.games',
    followers_count: 6900,
    following_count: 520,
    connections_count: 480,
    posts_count: 178,
    created_at: '2023-10-04T08:00:00Z',
    updated_at: '2023-10-04T08:00:00Z',
  },
  {
    id: 'p14',
    username: 'emmanuel.kiprop',
    full_name: 'Emmanuel Kiprop',
    first_name: 'Emmanuel',
    last_name: 'Kiprop',
    avatar_url: '/avatars/brian.jpg',
    cover_url: null,
    bio: 'Eco-tourism expedition lead & founder of Nairobi Cycling Collective. Passionate about sustainable urban transit & cycling Karura.',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2321,
    longitude: 36.8264,
    account_type: 'personal',
    is_verified: false,
    is_private: false,
    website: null,
    followers_count: 4300,
    following_count: 380,
    connections_count: 410,
    posts_count: 92,
    created_at: '2024-01-20T08:00:00Z',
    updated_at: '2024-01-20T08:00:00Z',
  },
]

// --- EVENTS ---
export const DEMO_EVENTS: Event[] = [
  {
    id: 'e1',
    host_id: 'p3',
    title: 'Nairobi Tech Summit — AI & Future of African Fintech',
    description: 'Join Nairobi\'s premier tech gathering bringing together founders, software engineers and investors to discuss the next wave of African AI and financial infrastructure. Featuring keynote speakers from Safaricom, Google Research Africa and PayAfrica.\n\nEnjoy networking, live tech demos, panel discussions, and evening refreshments.',
    cover_url: null,
    start_date: '2026-09-27T14:00:00Z',
    end_date: '2026-09-27T19:00:00Z',
    venue_name: 'iHub Nairobi',
    address: 'Bishop Magua Centre, Ngong Road',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3028,
    longitude: 36.7849,
    category: 'technology',
    capacity: 250,
    is_free: true,
    price: null,
    currency: 'KES',
    is_online: false,
    online_url: null,
    attendees_count: 184,
    interested_count: 112,
    created_at: '2026-09-01T08:00:00Z',
    host: DEMO_PROFILES[2],
  },
  {
    id: 'e2',
    host_id: 'p2',
    title: 'Karura Forest Golden Hour Photography Walk',
    description: 'A guided sunset photography exploration through Karura Forest. We will capture waterfall reflections, forest canopy light-rays and native bird species. Open to mobile photographers, mirrorless users, and seasoned pros.\n\nMeet at Gate C on Limuru Road. Complimentary chai and photography cheat-sheets provided.',
    cover_url: null,
    start_date: '2026-09-28T16:00:00Z',
    end_date: '2026-09-28T18:45:00Z',
    venue_name: 'Karura Forest Gate C',
    address: 'Limuru Road, Karura',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2321,
    longitude: 36.8264,
    category: 'photography',
    capacity: 35,
    is_free: false,
    price: 500,
    currency: 'KES',
    is_online: false,
    online_url: null,
    attendees_count: 32,
    interested_count: 64,
    created_at: '2026-09-05T08:00:00Z',
    host: DEMO_PROFILES[1],
  },
  {
    id: 'e3',
    host_id: 'p3',
    title: 'Silicon Savannah Founders & Angel Pitch Night',
    description: 'An exclusive networking evening for early-stage African founders and angel syndicates. Hear lightning pitches from 5 pre-seed African startups, exchange learnings on scaling across Kenya and Nigeria, and build relationships with leading regional VCs.\n\nHosted at The Alchemist in Westlands with craft drinks and food.',
    cover_url: null,
    start_date: '2026-09-26T18:00:00Z',
    end_date: '2026-09-26T22:30:00Z',
    venue_name: 'The Alchemist Westlands',
    address: 'Parklands Road, Westlands',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2684,
    longitude: 36.8069,
    category: 'business',
    capacity: 100,
    is_free: false,
    price: 1500,
    currency: 'KES',
    is_online: false,
    online_url: null,
    attendees_count: 86,
    interested_count: 145,
    created_at: '2026-09-02T08:00:00Z',
    host: DEMO_PROFILES[2],
  },
  {
    id: 'e4',
    host_id: 'p6',
    title: 'Sunday Ngong Hills 7-Knuckles Trail Hike',
    description: 'Experience one of Kenya\'s most iconic hikes across the rolling green knolls of Ngong Hills. Enjoy fresh highland air, stunning views of the Great Rift Valley, and great camaraderie.\n\nDistance: 12km. Moderate fitness level. Guided group pace with designated trail captains. Transport departs Nairobi CBD at 6:30 AM.',
    cover_url: null,
    start_date: '2026-09-29T06:30:00Z',
    end_date: '2026-09-29T13:00:00Z',
    venue_name: 'Ngong Hills Main Gate',
    address: 'Ngong Hills Nature Reserve, Kajiado',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3833,
    longitude: 36.6333,
    category: 'fitness',
    capacity: 60,
    is_free: true,
    price: null,
    currency: 'KES',
    is_online: false,
    online_url: null,
    attendees_count: 54,
    interested_count: 98,
    created_at: '2026-09-08T08:00:00Z',
    host: DEMO_PROFILES[5],
  },
  {
    id: 'e5',
    host_id: 'p5',
    title: 'Nairobi Afro-Soul & Live Creative Sessions',
    description: 'An intimate creative evening celebrating Nairobi\'s rising musicians, poets, and visual artists. Featuring live acoustic sets, experimental Afro-fusion beats, and open jam sessions.\n\nHosted by Aisha Mwangi at the iconic GoDown Arts Centre in Industrial Area.',
    cover_url: null,
    start_date: '2026-10-02T19:00:00Z',
    end_date: '2026-10-02T23:30:00Z',
    venue_name: 'GoDown Arts Centre',
    address: 'Enterprise Road, Industrial Area',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3045,
    longitude: 36.8333,
    category: 'art',
    capacity: 160,
    is_free: false,
    price: 800,
    currency: 'KES',
    is_online: false,
    online_url: null,
    attendees_count: 138,
    interested_count: 220,
    created_at: '2026-09-10T08:00:00Z',
    host: DEMO_PROFILES[4],
  },
  {
    id: 'e6',
    host_id: 'p1',
    title: 'Design Systems & Product UX Workshop',
    description: 'A hands-on masterclass for product designers, engineers, and founders. Learn how to architect scalable design systems, conduct user research tailored to African markets, and optimize for low-bandwidth mobile environments.\n\nBring your laptop. Interactive Figma templates and lunch included.',
    cover_url: null,
    start_date: '2026-10-04T09:30:00Z',
    end_date: '2026-10-04T16:30:00Z',
    venue_name: 'The Tent at Village Market',
    address: 'Village Market, Gigiri',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2286,
    longitude: 36.8093,
    category: 'education',
    capacity: 45,
    is_free: false,
    price: 3000,
    currency: 'KES',
    is_online: false,
    online_url: null,
    attendees_count: 38,
    interested_count: 72,
    created_at: '2026-09-12T08:00:00Z',
    host: DEMO_PROFILES[0],
  },
  {
    id: 'e7',
    host_id: 'p8',
    title: 'Kenya AI & Low-Resource Language Hackathon',
    description: 'A 24-hour sprint developing AI applications, voice interfaces, and LLM fine-tuning for Swahili, Sheng, and East African local languages. Compete for KES 500,000 in prizes and cloud credits.\n\nMentors from Google Research Africa and Nairobi AI Lab.',
    cover_url: null,
    start_date: '2026-10-10T08:00:00Z',
    end_date: '2026-10-11T12:00:00Z',
    venue_name: 'iHub Nairobi',
    address: 'Bishop Magua Centre, Ngong Road',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3028,
    longitude: 36.7849,
    category: 'technology',
    capacity: 120,
    is_free: true,
    price: null,
    currency: 'KES',
    is_online: false,
    online_url: null,
    attendees_count: 104,
    interested_count: 175,
    created_at: '2026-09-14T08:00:00Z',
    host: DEMO_PROFILES[7],
  },
  {
    id: 'e8',
    host_id: 'p11',
    title: 'Specialty Coffee Cupping & Brewing Masterclass',
    description: 'Discover the distinct terroir of Kenyan specialty coffee. Taste single-origin varieties from Nyeri, Kirinyaga, and Mt. Kenya. Learn espresso extraction and manual pour-over techniques from Kenya Barista Champion Juma Omondi.',
    cover_url: null,
    start_date: '2026-10-17T10:00:00Z',
    end_date: '2026-10-17T13:00:00Z',
    venue_name: 'Nairobi Coffee Roasters',
    address: 'Marula Lane, Karen',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3197,
    longitude: 36.7065,
    category: 'food',
    capacity: 25,
    is_free: false,
    price: 1800,
    currency: 'KES',
    is_online: false,
    online_url: null,
    attendees_count: 22,
    interested_count: 45,
    created_at: '2026-09-15T08:00:00Z',
    host: DEMO_PROFILES[10],
  },
  {
    id: 'e9',
    host_id: 'p12',
    title: 'Nairobi National Park Sunrise Wildlife Photowalk',
    description: 'An exclusive dawn safari game drive and photography workshop inside Nairobi National Park. Photograph lions, rhinos, and giraffes against the dramatic morning silhouette of the Nairobi city skyline.\n\nIncludes 4x4 open-roof safari van, KWS park entry assistance, and wildlife telephoto coaching.',
    cover_url: null,
    start_date: '2026-10-18T05:30:00Z',
    end_date: '2026-10-18T11:00:00Z',
    venue_name: 'Nairobi National Park Main Gate',
    address: 'Lang\'ata Road, Nairobi',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3650,
    longitude: 36.8500,
    category: 'photography',
    capacity: 20,
    is_free: false,
    price: 3500,
    currency: 'KES',
    is_online: false,
    online_url: null,
    attendees_count: 19,
    interested_count: 58,
    created_at: '2026-09-16T08:00:00Z',
    host: DEMO_PROFILES[11],
  },
]

// --- COMMUNITIES ---
export const DEMO_COMMUNITIES: Community[] = [
  {
    id: 'c1',
    creator_id: 'p2',
    name: 'Nairobi Creatives',
    slug: 'nairobi-creatives',
    description: 'A vibrant collective of African illustrators, visual artists, UI designers, filmmakers, and photographers in Nairobi. Share your latest work, find paid gigs, collaborate on projects, and grow your creative career.',
    cover_url: null,
    avatar_url: '/avatars/kwame.jpg',
    category: 'Art',
    is_private: false,
    members_count: 3840,
    posts_count: 1420,
    events_count: 42,
    created_at: '2023-01-10T08:00:00Z',
    creator: DEMO_PROFILES[1],
  },
  {
    id: 'c2',
    creator_id: 'p4',
    name: 'Silicon Savannah Tech Community',
    slug: 'silicon-savannah',
    description: 'Kenya\'s largest community of software engineers, cloud architects, mobile developers, and technical leaders. Deep dives into Next.js, Go, Rust, M-Pesa APIs, system design, and tech careers.',
    cover_url: null,
    avatar_url: '/avatars/david.jpg',
    category: 'Technology',
    is_private: false,
    members_count: 11450,
    posts_count: 5820,
    events_count: 112,
    created_at: '2022-06-15T08:00:00Z',
    creator: DEMO_PROFILES[3],
  },
  {
    id: 'c3',
    creator_id: 'p2',
    name: 'Nairobi Photographers Circle',
    slug: 'nairobi-photographers',
    description: 'From street photography in Nairobi CBD to wildlife in the Mara and landscape shoots in the Rift Valley. Gear discussions, photo critiques, model casting, and monthly photowalks.',
    cover_url: null,
    avatar_url: '/avatars/kwame.jpg',
    category: 'Photography',
    is_private: false,
    members_count: 2480,
    posts_count: 3890,
    events_count: 31,
    created_at: '2023-03-20T08:00:00Z',
    creator: DEMO_PROFILES[1],
  },
  {
    id: 'c4',
    creator_id: 'p3',
    name: 'Kenya Startup Founders & Angels',
    slug: 'startup-kenya',
    description: 'The hub for African venture-backed startups, pre-seed founders, and angel investors. Pitching, legal structuring, fundraising strategies, cross-border expansion, and founder mental wellness.',
    cover_url: null,
    avatar_url: '/avatars/sadia.jpg',
    category: 'Business',
    is_private: false,
    members_count: 6720,
    posts_count: 2890,
    events_count: 74,
    created_at: '2022-11-01T08:00:00Z',
    creator: DEMO_PROFILES[2],
  },
  {
    id: 'c5',
    creator_id: 'p6',
    name: 'Weekend Explorers Nairobi',
    slug: 'weekend-explorers',
    description: 'Nairobi\'s outdoor adventurers club. Weekend hikes through Karura, Ngong Hills, Mount Longonot, Ol Donyo Sabuk, and camping trips to Naivasha. Leave no trace, hike together.',
    cover_url: null,
    avatar_url: '/avatars/brian.jpg',
    category: 'Fitness',
    is_private: false,
    members_count: 2150,
    posts_count: 1120,
    events_count: 88,
    created_at: '2023-05-05T08:00:00Z',
    creator: DEMO_PROFILES[5],
  },
  {
    id: 'c6',
    creator_id: 'p9',
    name: 'Nairobi Women in Tech',
    slug: 'nairobi-women-tech',
    description: 'Empowering African women in engineering, product management, data science, and tech entrepreneurship. Mentorship circles, salary negotiation workshops, and leadership masterclasses.',
    cover_url: null,
    avatar_url: '/avatars/sharon.jpg',
    category: 'Technology',
    is_private: false,
    members_count: 4890,
    posts_count: 2140,
    events_count: 53,
    created_at: '2023-04-18T08:00:00Z',
    creator: DEMO_PROFILES[8],
  },
  {
    id: 'c7',
    creator_id: 'p11',
    name: 'Kenyan Specialty Coffee Club',
    slug: 'kenya-coffee-club',
    description: 'Celebrating world-renowned Kenyan coffee culture. Exploring specialty cafes in Karen, Westlands, and Gigiri. Home-brewing guides, farm visits, and barista community meetups.',
    cover_url: null,
    avatar_url: '/avatars/juma.jpg',
    category: 'Food',
    is_private: false,
    members_count: 3120,
    posts_count: 1450,
    events_count: 36,
    created_at: '2023-07-29T08:00:00Z',
    creator: DEMO_PROFILES[10],
  },
  {
    id: 'c8',
    creator_id: 'p13',
    name: 'Nairobi Game Devs & Animators',
    slug: 'nairobi-game-devs',
    description: 'Building the next generation of African indie video games and 3D animations. Game jams, Blender asset swaps, Unity/Unreal Engine workshops, and gaming industry networking in Kenya.',
    cover_url: null,
    avatar_url: '/avatars/dennis.jpg',
    category: 'Gaming',
    is_private: false,
    members_count: 1890,
    posts_count: 980,
    events_count: 28,
    created_at: '2023-10-04T08:00:00Z',
    creator: DEMO_PROFILES[12],
  },
]

// --- ACTIVITIES ---
export const DEMO_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    creator_id: 'p6',
    title: 'Sunday Morning Ngong Hills Ridge Hike',
    description: 'Join us every Sunday for guided scenic group hikes across the iconic 7 knolls of Ngong Hills.',
    category: 'Fitness',
    city: 'Nairobi',
    country: 'Kenya',
    participants_count: 286,
    image_url: null,
    created_at: '2024-01-01T08:00:00Z',
  },
  {
    id: 'a2',
    creator_id: 'p2',
    title: 'Karura Forest Sunrise Photowalk',
    description: 'Weekly morning photowalk capturing the golden sunbeams, bamboo trails, and waterfalls of Karura Forest.',
    category: 'Photography',
    city: 'Nairobi',
    country: 'Kenya',
    participants_count: 124,
    image_url: null,
    created_at: '2024-01-15T08:00:00Z',
  },
  {
    id: 'a3',
    creator_id: 'p7',
    title: 'Uhuru Park Sunset Yoga & Breathwork',
    description: 'Unwind your weekday with open-air yoga, mindfulness and breathwork overlooking the Nairobi skyline.',
    category: 'Wellness',
    city: 'Nairobi',
    country: 'Kenya',
    participants_count: 85,
    image_url: null,
    created_at: '2024-02-01T08:00:00Z',
  },
  {
    id: 'a4',
    creator_id: 'p3',
    title: 'Wednesday Founders Coffee at Java Westlands',
    description: 'Casual, high-value breakfast and coffee meetups for startup founders and tech builders.',
    category: 'Business',
    city: 'Nairobi',
    country: 'Kenya',
    participants_count: 172,
    image_url: null,
    created_at: '2024-01-20T08:00:00Z',
  },
  {
    id: 'a5',
    creator_id: 'p1',
    title: 'Weekly UX Critique & UI Teardown at iHub',
    description: 'Bring your Figma prototypes or live mobile apps. Get constructive feedback from senior Nairobi designers.',
    category: 'Design',
    city: 'Nairobi',
    country: 'Kenya',
    participants_count: 148,
    image_url: null,
    created_at: '2024-03-01T08:00:00Z',
  },
  {
    id: 'a6',
    creator_id: 'p14',
    title: 'Saturday Nairobi Cycling Peloton',
    description: 'Weekend group cycling ride along the Southern Bypass and Northern Bypass. Helmets mandatory.',
    category: 'Fitness',
    city: 'Nairobi',
    country: 'Kenya',
    participants_count: 96,
    image_url: null,
    created_at: '2024-02-15T08:00:00Z',
  },
]

// --- PLACES ---
export const DEMO_PLACES: Place[] = [
  {
    id: 'pl1',
    name: 'iHub Nairobi',
    description: 'Kenya\'s pioneering technology innovation hub. The epicentre of African tech startups, developer communities, and hackathons.',
    category: 'coworking',
    image_url: null,
    address: 'Bishop Magua Centre, Ngong Road',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3028,
    longitude: 36.7849,
    rating: 4.8,
    events_count: 124,
    interested_count: 3410,
    created_at: '2024-01-01T08:00:00Z',
  },
  {
    id: 'pl2',
    name: 'The Alchemist Westlands',
    description: 'Nairobi\'s creative cultural oasis. Live music, outdoor cinema, food truck park, art installations, and unforgettable social nights.',
    category: 'venue',
    image_url: null,
    address: 'Parklands Road, Westlands',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2684,
    longitude: 36.8069,
    rating: 4.7,
    events_count: 186,
    interested_count: 7240,
    created_at: '2024-01-01T08:00:00Z',
  },
  {
    id: 'pl3',
    name: 'Karura Forest Sanctuary',
    description: '1,000 hectares of indigenous green forest right inside Nairobi. Featuring walking and biking trails, waterfalls, and caves.',
    category: 'park',
    image_url: null,
    address: 'Limuru Road, Karura',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2321,
    longitude: 36.8264,
    rating: 4.9,
    events_count: 78,
    interested_count: 10540,
    created_at: '2024-01-01T08:00:00Z',
  },
  {
    id: 'pl4',
    name: 'GoDown Arts Centre',
    description: 'A multi-disciplinary creative arts hub celebrating African contemporary visual arts, traditional dance, and live music.',
    category: 'gallery',
    image_url: null,
    address: 'Enterprise Road, Industrial Area',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3045,
    longitude: 36.8333,
    rating: 4.6,
    events_count: 92,
    interested_count: 4180,
    created_at: '2024-01-01T08:00:00Z',
  },
  {
    id: 'pl5',
    name: 'Nairobi National Park',
    description: 'The only wildlife capital national park in the world where lions and rhinos roam against a modern city skyscraper backdrop.',
    category: 'park',
    image_url: null,
    address: 'Lang\'ata Road',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.3650,
    longitude: 36.8500,
    rating: 4.9,
    events_count: 45,
    interested_count: 8900,
    created_at: '2024-01-01T08:00:00Z',
  },
  {
    id: 'pl6',
    name: 'KICC Rooftop & Helipad',
    description: 'Iconic 360-degree panoramic vantage point of the entire Nairobi metropolitan skyline. Nairobi\'s favorite golden hour meetup spot.',
    category: 'venue',
    image_url: null,
    address: 'Harambee Avenue, Nairobi CBD',
    city: 'Nairobi',
    country: 'Kenya',
    latitude: -1.2884,
    longitude: 36.8233,
    rating: 4.7,
    events_count: 58,
    interested_count: 5120,
    created_at: '2024-01-01T08:00:00Z',
  },
]

// --- NOTIFICATIONS ---
export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    user_id: 'current',
    type: 'new_follower',
    title: 'New Follower',
    body: 'Amara Wanjiku started following you',
    actor_id: 'p1',
    reference_id: null,
    reference_type: null,
    is_read: false,
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    actor: DEMO_PROFILES[0],
  },
  {
    id: 'n2',
    user_id: 'current',
    type: 'post_liked',
    title: 'New Like',
    body: 'Kwame Mensah liked your Karura photowalk update',
    actor_id: 'p2',
    reference_id: null,
    reference_type: 'post',
    is_read: false,
    created_at: new Date(Date.now() - 23 * 60 * 1000).toISOString(),
    actor: DEMO_PROFILES[1],
  },
  {
    id: 'n3',
    user_id: 'current',
    type: 'event_joined',
    title: 'Event Update',
    body: 'Sadia Ibrahim joined the Silicon Savannah Founders Pitch Night',
    actor_id: 'p3',
    reference_id: 'e3',
    reference_type: 'event',
    is_read: true,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    actor: DEMO_PROFILES[2],
  },
  {
    id: 'n4',
    user_id: 'current',
    type: 'new_connection',
    title: 'Connection Request',
    body: 'David Kamau from Safaricom wants to connect with you',
    actor_id: 'p4',
    reference_id: null,
    reference_type: null,
    is_read: true,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    actor: DEMO_PROFILES[3],
  },
  {
    id: 'n5',
    user_id: 'current',
    type: 'community_invitation',
    title: 'Community Invite',
    body: 'Sharon Achieng invited you to join Nairobi Women in Tech',
    actor_id: 'p9',
    reference_id: 'c6',
    reference_type: 'community',
    is_read: true,
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    actor: DEMO_PROFILES[8],
  },
]

// --- POSTS (Real-time Feed from Connections) ---
export const DEMO_POSTS: Post[] = [
  {
    id: 'post-1',
    author_id: 'p2',
    author: DEMO_PROFILES[1], // Kwame Mensah
    content: "Morning light hitting the canopy at Karura Forest today was pure magic. We wrapped our sunrise walk with 24 photographers from the Nairobi community. The creative energy in this city is unmatched right now! 📸🇰🇪",
    location: "Karura Forest Reserve, Nairobi",
    category: "Photography",
    likes_count: 142,
    comments_count: 18,
    shares_count: 24,
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(), // 12m ago
    is_liked: false,
    is_saved: false,
    tags: ['NairobiPhotography', 'KaruraForest', 'CreativesKE'],
    event_link: {
      id: 'e2',
      title: 'Karura Forest Golden Hour Photography Walk',
      date: 'Sunday • 6:30 AM',
      venue: 'Karura Forest Gate A'
    },
    comments: [
      {
        id: 'c1',
        post_id: 'post-1',
        author_id: 'p1',
        author: DEMO_PROFILES[0], // Amara Wanjiku
        content: "The lighting in the canopy shots is stunning Kwame! Next time I'm bringing the UI design team along.",
        created_at: new Date(Date.now() - 9 * 60 * 1000).toISOString()
      },
      {
        id: 'c2',
        post_id: 'post-1',
        author_id: 'p6',
        author: DEMO_PROFILES[5], // Brian Kipkemboi
        content: "Saw you guys on the 10km trail! Looked like an awesome session.",
        created_at: new Date(Date.now() - 4 * 60 * 1000).toISOString()
      }
    ]
  },
  {
    id: 'post-2',
    author_id: 'p3',
    author: DEMO_PROFILES[2], // Sadia Ibrahim
    content: "Big milestone for PayAfrica today! We just crossed 100,000 active cross-border merchant transactions across East Africa. Huge shoutout to the tech ecosystem in Nairobi and all our local partners in Upper Hill and Westlands.",
    location: "Upper Hill Financial District, Nairobi",
    category: "Business",
    likes_count: 289,
    comments_count: 34,
    shares_count: 51,
    created_at: new Date(Date.now() - 34 * 60 * 1000).toISOString(), // 34m ago
    is_liked: true,
    is_saved: true,
    tags: ['FintechAfrica', 'PayAfrica', 'SiliconSavannah'],
    event_link: {
      id: 'e3',
      title: 'Silicon Savannah Founders & Angels Pitch Night',
      date: 'Thursday • 6:00 PM',
      venue: 'The Alchemist Westlands'
    },
    comments: [
      {
        id: 'c3',
        post_id: 'post-2',
        author_id: 'p4',
        author: DEMO_PROFILES[3], // David Kamau
        content: "Huge congratulations Sadia and team! Proud of what you're building out of Nairobi.",
        created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString()
      },
      {
        id: 'c4',
        post_id: 'post-2',
        author_id: 'p8',
        author: DEMO_PROFILES[7], // Tariq Otieno
        content: "Incredible growth trajectory. Looking forward to our AI fraud detection pilot next month.",
        created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString()
      }
    ]
  },
  {
    id: 'post-3',
    author_id: 'p1',
    author: DEMO_PROFILES[0], // Amara Wanjiku
    content: "Just wrapped up our design sprint at iHub Kilimani on mobile design systems tailored specifically for low-bandwidth environments. Designing for the next 100 million African smartphone users requires stripping away the noise and focusing on pure utility and clarity.",
    location: "iHub Nairobi, Senteu Plaza",
    category: "Technology",
    likes_count: 195,
    comments_count: 22,
    shares_count: 16,
    created_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(), // ~1h ago
    is_liked: false,
    is_saved: false,
    tags: ['ProductDesign', 'iHubNairobi', 'DesignSystems'],
    comments: [
      {
        id: 'c5',
        post_id: 'post-3',
        author_id: 'p7',
        author: DEMO_PROFILES[6], // Faith Chebet
        content: "This is crucial for our farmers using ShambaPulse in rural Kenya. Simplicity saves lives and livelihoods.",
        created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString()
      }
    ]
  },
  {
    id: 'post-4',
    author_id: 'p6',
    author: DEMO_PROFILES[5], // Brian Kipkemboi
    content: "Sunday morning run squad! We clocked 21km on the scenic Ngong Hills ridge line. Elevation was tough, but the view of the Great Rift Valley at 2,460m makes every single stride worth it. Who is joining our next trail run?",
    location: "Ngong Hills Forest Reserve",
    category: "Fitness",
    likes_count: 210,
    comments_count: 27,
    shares_count: 9,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2h ago
    is_liked: false,
    is_saved: false,
    tags: ['NgongHills', 'TrailRunningKE', 'NairobiFitness'],
    event_link: {
      id: 'e4',
      title: 'Sunday Morning Trail Hike & Run — Ngong Hills',
      date: 'Sunday • 7:00 AM',
      venue: 'Ngong Hills Forest Gate'
    },
    comments: []
  },
  {
    id: 'post-5',
    author_id: 'p4',
    author: DEMO_PROFILES[3], // David Kamau
    content: "Deploying our high-throughput payment settlement microservices on Kubernetes today at Safaricom HQ. Handling over 30,000 transactions per second during peak hours with sub-50ms latency. The scale of financial infrastructure built right here in Kenya is world-class.",
    location: "Safaricom HQ, Ngong Road",
    category: "Technology",
    likes_count: 312,
    comments_count: 41,
    shares_count: 38,
    created_at: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(), // 3.5h ago
    is_liked: false,
    is_saved: false,
    tags: ['CloudNative', 'Safaricom', 'MPesa', 'DevOpsKE'],
    comments: []
  },
  {
    id: 'post-6',
    author_id: 'p5',
    author: DEMO_PROFILES[4], // Aisha Mwangi
    content: "Sound check ready at GoDown Arts Centre! Tonight's set blends traditional Nyatiti strings with deep Afro-house synths and live vocals. Can't wait to see everyone who RSVP'd on MEET!",
    location: "GoDown Arts Centre, Industrial Area",
    category: "Music",
    likes_count: 178,
    comments_count: 19,
    shares_count: 12,
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(), // 5h ago
    is_liked: true,
    is_saved: false,
    tags: ['AfroHouse', 'LiveMusicKE', 'GoDownArts'],
    event_link: {
      id: 'e5',
      title: 'Afro-Acoustic Live Jam Session — GoDown Arts',
      date: 'Friday • 7:30 PM',
      venue: 'GoDown Arts Centre'
    },
    comments: []
  },
  {
    id: 'post-7',
    author_id: 'p9',
    author: DEMO_PROFILES[8], // Sharon Achieng
    content: "Mentoring 40 brilliant young women at our Nairobi Women in Tech hackathon today at Westlands! The solutions they are building in healthtech, agritech and climate resilience are mind-blowing. The future of African tech is female. 💪🇰🇪",
    location: "Westlands, Nairobi",
    category: "Community",
    likes_count: 345,
    comments_count: 38,
    shares_count: 47,
    created_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    is_liked: false,
    is_saved: false,
    tags: ['WomenInTech', 'NairobiWomenInTech', 'DiversityInTech'],
    comments: []
  },
  {
    id: 'post-8',
    author_id: 'p11',
    author: DEMO_PROFILES[10], // Juma Omondi
    content: "Fresh batch of washed SL28 from Nyeri just roasted at our Karen lab. Jasmine floral aromas with blackcurrant acidity. Come through this weekend for a complimentary cupping session!",
    location: "Java House Roastery, Karen",
    category: "Food & Drink",
    likes_count: 154,
    comments_count: 15,
    shares_count: 8,
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    is_liked: false,
    is_saved: false,
    tags: ['SpecialtyCoffee', 'KenyaCoffee', 'KarenNairobi'],
    comments: []
  }
]

